"""update: updated_at on all models

Revision ID: 34c5b20c5e6d
Revises: b93ba8ecc5ef
Create Date: 2023-05-22 14:50:24.613382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c5b20c5e6d'
down_revision = 'b93ba8ecc5ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
