"""add: b64 qr code to user

Revision ID: 466295dffa6d
Revises: ca31fd71a743
Create Date: 2023-05-10 09:29:34.299975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466295dffa6d'
down_revision = 'ca31fd71a743'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qr_code_b64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qr_code_b64')
    # ### end Alembic commands ###
