"""deleted testing models

Revision ID: 6a825a6d46ec
Revises: 46f3b761ef67
Create Date: 2023-04-20 09:30:19.635496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a825a6d46ec'
down_revision = '46f3b761ef67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
