"""fix unique email bug in attendance

Revision ID: a21a5b06ec24
Revises: 59837ceb1cb5
Create Date: 2023-04-28 07:03:22.041005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21a5b06ec24'
down_revision = '59837ceb1cb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_attendance_history_email', table_name='attendance_history')
    op.drop_index('ix_attendance_history_id', table_name='attendance_history')
    op.drop_table('attendance_history')
    op.drop_index('ix_locations_address', table_name='locations')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_index('ix_locations_name', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_name', 'locations', ['name'], unique=False)
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_index('ix_locations_address', 'locations', ['address'], unique=False)
    op.create_table('attendance_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('image_encoding', sa.TEXT(), nullable=True),
    sa.Column('face_encoding', sa.TEXT(), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(), nullable=True),
    sa.Column('qr_code_content', sa.TEXT(), nullable=True),
    sa.Column('is_signed_in', sa.BOOLEAN(), nullable=False),
    sa.Column('is_signed_out', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_history_id', 'attendance_history', ['id'], unique=False)
    op.create_index('ix_attendance_history_email', 'attendance_history', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('image_encoding', sa.TEXT(), nullable=True),
    sa.Column('face_encoding', sa.TEXT(), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(), nullable=True),
    sa.Column('qr_code_content', sa.TEXT(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
