name: Docker Image CI

on:
  push:
    branches: [ "lban" ]
  pull_request:
    branches: [ "lban" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry using Docker
      run: docker login osreglban.azurecr.io --username ${{ secrets.OS_REG_USERNAME }} --password ${{ secrets.OS_REG_PASSWORD }}
    
    - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --file Dockerfile --tag fastams:lban
      
    - name: Tag the Docker Image
      run: docker tag fastams osreglban.azurecr.io/fastams
      
    - name: Push the Docker Image to Azure Container Registry
      run: docker push osreglban.azurecr.io/fastams
  
